rules:
  class-name-format: 0
  variable-name-format: 0
  mixins-before-declarations: 0

files:
    ignore:
      - '**/x-foo.scss'
      - '**/breakpoints.scss'
      - '**/reset.scss'
      - '**/typography.scss'
      - '**/freestyle-palette-item.scss'
